### ISSUE TITLE
Recordings of the talks. 

### ISSUE THREAD

**Issue by NobbZ** [hh-ex/planning#11]
Even living near Hamburg, I do have a hard time joining the meetups due to family duties. Are there any plans of recording and publishing the talks given?

**Comment by OleMchls** [comment]
Hey @NobbZ while I totally see your point, I see quite some obstacles to overcome here:
First, we do not have any recoding equipment, and equipment at hand might and will differ per location. Second, I personally do not have the time to organise recordings/equiment and take care of the editing. 

I'd totally be in, if we find someone who'd volunteer for organizing. On the other hand we planned hh.ex to not have that talk heavy focus. We want to do lots of discussions and coding katas. Where a recoding would not help at all. And properly events like Elixir Conf eu and ElixirDaze have more talks, and also properly talks with conference level preparation. So you also might want to consider checking out their videos: http://confreaks.tv/conferences/elixirdaze

I'm going to close this issue here. If someone want to jump in this, please let me know!
