### ISSUE TITLE
June Edition

### ISSUE THREAD

**Issue by LydG** [hh-ex/planning#16]
- [x] Create meetup.com event
- [x] Agenda
- [x] prepare katas if applicable
- [x] Location
- [x] Announce meetup.com event (triggers mail)
- **Date:** June 28th
- **Location:** Ubilabs @KlausTrainer 

Agenda:
- 18:00 Open the doors 
- 18:30 Welcome 
- Show your elixir production apps
- Kata
- Hang out and have beers, coke, mate or whats-o-ever 🍻

**Comment by OleMchls** [comment]
Talking about the location, Jimdo is unfortunately not available this month. So we would need a different location. Paging @dszam here, would SABIO be a option? If not, we could again meet at Xing? @BjRo ?

**Comment by OleMchls** [comment]
Also talking about the agenda. One thing we wanted to do, is talking about Elixir in Production. What does that mean: I'd like to invite everyone who already runs a Elixir app in production, to show everyone a little demo and answering a hand full of questions, showing why Elixir in this case is and was a great choice. Here is the list of questions I thought of:
- What does your app do? (Give some context about the business)
- What does it look like?
- How does it perform?
- What did you learned while building it?
- Why did you choose Elixir?
- What Elixir feature amazed / disappointed you while writing the app?
- What do you deploy it?

In general I'd like to see if people would show something more then code. But code is also great :D In order to fit more apps into this program slot, one app spotlight should not take longer than 10 minutes.

I will volunteer and show our Elixir app we run at Jimdo. But we need more, so calling @BjRo @h4cc @dszam @arvidkahl here! Please also post

**Comment by narrowtux** [comment]
I work with @arvidkahl and we always wanted to contribute something to a meetup. I'll talk to him about what we could show.

**Comment by KlausTrainer** [comment]
I can also offer hosting the meetup at Ubilabs.

**Comment by OleMchls** [comment]
Yay! Ubilabs would be awesome!

**Comment by OleMchls** [comment]
@narrowtux yes please :)

**Comment by OleMchls** [comment]
@KlausTrainer do you need to double check or could I just go ahead and announce the venue? Because with that agenda and location would be set :)

**Comment by KlausTrainer** [comment]
@nesQuick No double check required, at least as long as I'm hosting it, which I'll happily do :) Feel free to announce!

**Comment by BjRo** [comment]
In principle I would like to talk a bit about our setup/app. I need to clarify though, how much I am allowed to show from our application. I'll ping you, if I get a green light.

**Comment by OleMchls** [comment]
I'd also happily take any pointers to people within our community who run a elixir app in production and would participate :)

@KlausTrainer  💖
@BjRo 👍

**Comment by OleMchls** [comment]
Just announced the meet up: http://www.meetup.com/Elixir-Hamburg/events/231538492/

**Comment by OleMchls** [comment]
@BjRo any news? 

So far I have @narrowtux and myself "on the list" I think we could do one more :) So if anyone knows some one, please send them here :D

**Comment by BjRo** [comment]
@nesQuick Unfortunately not. I'm in the process of clarifying. Will come back to you in the next few days.

**Comment by nesQuick** [comment]
✨

**Comment by narrowtux** [comment]
I talked with Arvid today and we agreed that we want to do something, we just don't know exactly what yet.

**Comment by OleMchls** [comment]
I think answering the questions above won't take that much preparation :)

**Comment by narrowtux** [comment]
True. I will use that as a guideline for the slides.

**Comment by BjRo** [comment]
From XING side we got a green light today. Unfortunately I won't be able to make it to the meetup though, because of a short notice private appoinment. 

Would have loved to show our app and also see the others. Maybe we can repeat this somewhere in the future?

**Comment by OleMchls** [comment]
@BjRo yeah, sure, I hope we can do this on a more regular basis. We _just_ need more people having a production Elixir app :)

**Comment by OleMchls** [comment]
As I just "figured" we need a kata, we have a a kata repository. @KlausTrainer could you moderate thou your [dtgcaa kata](https://github.com/hh-ex/kata-dtgcaa)?

**Comment by OleMchls** [comment]
Otherwise I'd just pull the [sleep sort kata](https://github.com/hh-ex/kata-sleepsort)

**Comment by KlausTrainer** [comment]
@nesQuick Yes, I can moderate the kata :)
