### ISSUE TITLE
Taming the API Scraper from hell

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#4]
by Sebastian @zweizeichen

**Comment by zweizeichen** [comment]
A small, informal (and hopefully fun) presentation on a 'high performance' API scraper I built a while ago.  It'll probably mainly deal with the various problems and their solutions I encountered while designing/writing this piece of software. I will show different approaches to the problem set while touching on topics like:
- OTP / GenServer / Supervisors
- memory-saving techniques
- simple performance analysis
- NIFs
- ZeroMQ and zlib
- 'smart' scraping
- oAuth fun
- ETS
- accidentally DoS'ing yourself
- ...and probably a couple more I forgot.

There are a lot of bits and pieces which might be useful for beginners and advanced developers alike, so that they won't hit the same roadblocks I hit.

Format: slides + maybe some code and discussion if you like
Time: ~30m-ish?

**Comment by OleMchls** [comment]
Awesome, thanks. I think we will pull this talk into one of the next meet ups. I really like not to plan too much ahead and the very next ones are already filled with a talk. And I really want to save the exciting content also for some later meetups  :)

**Comment by OleMchls** [comment]
@zweizeichen would you be up for his one in May?

**Comment by zweizeichen** [comment]
Sounds great! I'll prepare the slides, maybe I can bring some code along for afterwards - I already have an idea.

**Comment by OleMchls** [comment]
Your abstract sounds kinda big. Please keep the two under 30 minutes. 

After the talk we wanted to do something different this time: https://github.com/hh-ex/planning/issues/7#issuecomment-215688774

**Comment by zweizeichen** [comment]
Yup - most of the topics might be a single slide anyway. I know that we planned to do a bring your code session afterwards - what I meant was that I might have code for that from the project I'll be presenting.

**Comment by igl** [comment]
@zweizeichen The talk is going to be in english right?

**Comment by zweizeichen** [comment]
I finished the slides yesterday and they are in English, however I can hold the talk in German if no one who prefers English is present.

**Comment by OleMchls** [comment]
Yup. That's the why is like to do it as well. English as default if everyone present speaks German we could do that as well :)

**Comment by igl** [comment]
I am trying to pursue some non-german coworkers to come and infect them with elixir. :) i am happy with english.

**Comment by OleMchls** [comment]
Do it. AS I said we default to English :)

**Comment by h4cc** [comment]
@zweizeichen I can recommend training the presentation in english more than once - will help for sure :)

**Comment by zweizeichen** [comment]
https://slidr.io/zweizeichen/taming-the-api-scraper-from-hell#1

**Comment by zweizeichen** [comment]
I guess we can close this now
