### ISSUE TITLE
Elixir Hack & Learn

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#64]
I recently saw this event from the Hamburg Rust community:

```
Rust Hack & Learn Nov 2018

Details
• What we'll do
Join us for another round of hacking and learning Rust! Pair up and solve some Katas, work on your latest Rust project or join the "newbie corner".

Everyone is welcome, from seasoned programmer to those still seeking an opportunity to write their first line of Rust. In the latter case, don't worry, we will help you getting set up and going.

Thoughtworks will kindly host us in their Hamburg office, Großer Burstah 46-48.

We will start at 6:30 pm with a short introduction and then start hacking until 9 pm. From 9 to 9:30 there will be time to present your results (if you like) and share your "lessons learned".

Requirements

Please bring a laptop, ideally with your favourite editor and a recent Rust stable already installed. If you can't bring one, you can certainly pair up with someone who brought theirs.
```

I think this idea is great and as Elixir is also a fairly new language with many people _just_ being interested it may be worth coping this great idea.

Any volunteers making this happen for a meetup in 2019?

**Comment by jh2** [comment]
:hand:

**Comment by OleMchls** [comment]
@jh2 Sweet! Let's talk about this at the October meet up.

**Comment by boddhisattva** [comment]
With some guidance from some members of the Ruby community and with the help of some people on the day of a meetup,  I had a wonderful opportunity to facilitate a Ruby meetup in Bangalore where people were paired in a combination of someone with more experience with someone with less experience to solve a Ruby exercise from Exercism.

I've blogged about my learnings from facilitating that meet up [here](https://medium.com/@mohnishgj/learnings-from-facilitating-a-ruby-meetup-where-people-solved-an-exercism-kata-via-pair-programming-39c78113b86b) with the intention to share the experiences of what worked for us so that if anyone tries to facilitate something similar in the future they could potentially consider to use what worked for us and add more improvements as they deem fit.

Exercism played a very important role in the success of the meetup as the exercise had an end goal with a number of failing tests to make pass before you have a working solution.

Just thought of sharing this as you're planning something along these lines. Wish you great success with the hands on meetup!

**Comment by OleMchls** [comment]
@jh2 I obviously missed the October meetup. Want to meet for a coffee somewhen next week in your office or close to it (https://www.publiccoffeeroasters.com/unsere-cafes/gemuetlich-und-historisch-brandstwiete-3/) to discuss this for January?

**Comment by jh2** [comment]
Sure, I'll email you my number so we can text about time.

**Comment by OleMchls** [comment]
We did this, @jh2 if you'd like to do this again. I just opened the issues unti Aug 2020 just jump into the edition issue and give your 🤚
